### PR TITLE
Fix allow merge of several graphs

### PR DESCRIPTION
**Pull request by tawiesn**
@MKaptein  #11 Allows to concatenate and merge in the same graph several times (in parallel). See image below:

image

The two top layers have been created with sclblonnx and then the big graph has been merged into twice (once for the left branch and once for the right branch). The idea was to do some experiments with naive "batch" inference.

### CODE REVIEW

**Comment by MKaptein** [comment]
Hi,

Thanks for working on this issue! It's a bit complicated how we would setup the "multi-merge" neatly. I definitely like the `append_unique_string` idea to generate unique node names during the merge which is useful. For a final commit please do make sure to add all the arguments to the docstring and explain your new functionality (we are trying to keep the docs tidy -- I would be happy to help).

Perhaps the easiest way of advancing this issue is to first work out the desired functionality in the discussion of the issue itself? The interface to this function is definitely not set in stone yet, and we might end up having multiple versions of merge for various use-cases. So, perhaps we can first work out some cases? (Also, I am trying to understand your desired case a bit better stil).

Thanks!

**Comment by tawiesn** [comment]
@MKaptein Thanks for your feedback. Let me explain the idea/use case. We might want to have several networks in parallel, e.g., provide a batch of images and run them through a network with parallel sub-networks as shown in the image above. The subnetworks (left and right branch) might have the same layout, but different weights (e.g., two object detectors with different target objects trained on). Sometimes it might be easier to have two well-trained networks rather than train a combined network from scratch. By merging networks in different combinations we also want to try out and challenge the NPU we are working with.
I agree that it might make sense to have several maybe more specialized versions of a merge routine.
Furthermore, unique node names will be a must have. It might make sense to give the user some control over the naming scheme of the nodes, since this might help debugging (e.g., when looking at the network graphs in netron).
Feel free to adapt or modify the pull request if something is useful for you. My time is somewhat limited. I guess, the best way to define the interface and scenarios would be to write minimal unit tests for those (test driven development...). What do you think?

**Comment by rogvidarge** [comment]
Very interesting! I am actually working on something similar. But my usecase is slightly different. I am merging outputs from two existing subgraphs together, and I'm supporting this by adding a "joiner_graph", so I'm assuming that the subgraphs pass some output to the joiner graph, which will then compute some operation on the input. How would this match with what you are already working on?

**Comment by MKaptein** [comment]
This idea of the joiner graph inspires a possible solution for a general “merge" that might be simple to use; what if we just make it easy for a subgraph to become a (temporary) “node", and hence it can be added to the graph like any other node. That way the joiner_graph would would itself just be a “node”, and the two other subgraph that need to be joined to it would be added just like any other two nodes are currently added to a graph. As long as the input and output names match the topology should be constructible. In any case, a good merge should support the jointer_graph use case.

**Comment by tawiesn** [comment]
@rogvidarge @MKaptein I like the ideas of subgraphs treated as "nodes" in a hierarchical manner. In general we would like to be able to connect arbitrary graphs as long as the interfaces matches. There are three main cases: 1) a simple concatenation of two graphs (one after the other). 2) The "split" use case, where we have one graph which splits into two separate gaphs as in my use case described above. 3) The "join" use case where the output of several subgraphs serves as input to a "join" graph. This would also be of interest for my use case (to join the graphs and their results to a joined master result in the end.
Most of the stuff necessary for the use cases above are probably already part of the pull request:
1) one definitely needs the possibility to give unique names to all nodes and connections within the sub-graph. There is a high risk, that several subgraphs share certain names. Furthermore, it makes debugging easier, if we allow to modify the node names in a subgraph. 2) I had to remove some of the consistency checks in the merge routine. In general we need more general checks that just make sure that the required output of graph 1 matches the input of graph 2. Does that make sense? I'm wondering whether it would make sense, to add routines "concatenate(g1,g2)", "split(g_input, g_output1, g_output2,...)" and "join(g_input1, g_input2, g_output)" which would call the general merge routine and implement the consistency checks for the specific use cases...

**Comment by MKaptein** [comment]
I agree on the three cases and I think this is a good way of looking at it; I guess one useful start would be to add tests for each of them (a rudimentary test of merge already exists, we should extend) and use these are our baseline. I was in some way hoping the “treating subgraphs as nodes” would defy having to explicitly create list of the inputs-outputs that need to be connected (just as this is the case when adding nodes to a graph). The existing names of the inputs and outputs for specific nodes would effectively allow you to construct the desired topology without explicit “merge-lists”. However, I definitely see your naming use case such that its useful to rename when reusing the same subgraph multiple times (perhaps both ideas can be combined, such that upon a single merge only the rename is explicitly provided?). I now also understand the less strict consistency checks you proposed (I was initially working with the idea that after a merge the resulting graph should be “done”; if that is not the case and after a merge the product might still be intermediate, things would change). 

I think the concat(), split(), and join() routines are actually a great proposal; those seem “user friendly” enough for me, and as far as I can judge they should facilitate pretty much any use case (the join() effectively replacing the current merge() and if indeed implemented as specific cases of a more general merge would not even break things).

**Comment by rogvidarge** [comment]
@tawiesn @MKaptein I agree with the concat, split, and join routine proposal. I can make a new pull request for a join function. 

By the way, how come we aren't making use of the logging library for logging errors or warnings etc.?

**Comment by rogvidarge** [comment]
However, since the functionality already proposed in the current issue actually include the join capabilities, would you rather that I fork the code by @tawiesn and create a pull request into his changes?

**Comment by MKaptein** [comment]
We took a number of the suggestions here in an overhaul of the merge functionality; see 
44c5078 (and some earlier commits). Thanks again for all the recommendations and comments; these have greatly inspired our new approach.

Admittedly, the merge is tricky because of the large number of possible options of merging edges, inputs, and outputs, and thus this will remain a bit of "work-in-progress"; please do add any additional thoughts you might have or highlight issues.

Thanks again!

**Pull request closed without merging**
